"""add initial models

Revision ID: e67e9b1eb8f5
Revises: 
Create Date: 2022-01-21 01:49:49.574907

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e67e9b1eb8f5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "todos",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user", sa.BigInteger(), nullable=True),
        sa.Column("task", sa.String(length=512), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user"], ["users.id"], name="fk_todos_users_id_user"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todos")
    op.drop_table("users")
    # ### end Alembic commands ###
